// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as PingProcedure from "../ping_procedure";

export type PingArgs = __Infer<typeof PingProcedure.params>;
export type PingResult = __Infer<typeof PingProcedure.returnType>;

