// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddCounterReducer from "../add_counter_reducer";
import ApproveZoneSearchReducer from "../approve_zone_search_reducer";
import CompleteZoneSearchReducer from "../complete_zone_search_reducer";
import CreateGameReducer from "../create_game_reducer";
import DenyZoneSearchReducer from "../deny_zone_search_reducer";
import DrawCardReducer from "../draw_card_reducer";
import DrawMultipleReducer from "../draw_multiple_reducer";
import EndTurnReducer from "../end_turn_reducer";
import ExchangeCardsReducer from "../exchange_cards_reducer";
import FlipCardReducer from "../flip_card_reducer";
import JoinAsSpectatorReducer from "../join_as_spectator_reducer";
import JoinGameReducer from "../join_game_reducer";
import LeaveGameReducer from "../leave_game_reducer";
import MeekCardReducer from "../meek_card_reducer";
import MoveCardReducer from "../move_card_reducer";
import MoveCardToBottomOfDeckReducer from "../move_card_to_bottom_of_deck_reducer";
import MoveCardToTopOfDeckReducer from "../move_card_to_top_of_deck_reducer";
import MoveCardsBatchReducer from "../move_cards_batch_reducer";
import MoveOpponentCardReducer from "../move_opponent_card_reducer";
import PregameAcknowledgeRollReducer from "../pregame_acknowledge_roll_reducer";
import PregameChangeDeckReducer from "../pregame_change_deck_reducer";
import PregameChooseFirstReducer from "../pregame_choose_first_reducer";
import PregameReadyReducer from "../pregame_ready_reducer";
import RemoveCounterReducer from "../remove_counter_reducer";
import RemoveTokenReducer from "../remove_token_reducer";
import RequestRematchReducer from "../request_rematch_reducer";
import RequestZoneSearchReducer from "../request_zone_search_reducer";
import ResignGameReducer from "../resign_game_reducer";
import RespondRematchReducer from "../respond_rematch_reducer";
import RollDiceReducer from "../roll_dice_reducer";
import SendChatReducer from "../send_chat_reducer";
import SetNoteReducer from "../set_note_reducer";
import SetPhaseReducer from "../set_phase_reducer";
import SetPlayerOptionReducer from "../set_player_option_reducer";
import ShuffleCardIntoDeckReducer from "../shuffle_card_into_deck_reducer";
import ShuffleDeckReducer from "../shuffle_deck_reducer";
import SpawnLostSoulReducer from "../spawn_lost_soul_reducer";
import UnmeekCardReducer from "../unmeek_card_reducer";
import UpdateCardPositionReducer from "../update_card_position_reducer";
import UpdateLobbyMessageReducer from "../update_lobby_message_reducer";

export type AddCounterParams = __Infer<typeof AddCounterReducer>;
export type ApproveZoneSearchParams = __Infer<typeof ApproveZoneSearchReducer>;
export type CompleteZoneSearchParams = __Infer<typeof CompleteZoneSearchReducer>;
export type CreateGameParams = __Infer<typeof CreateGameReducer>;
export type DenyZoneSearchParams = __Infer<typeof DenyZoneSearchReducer>;
export type DrawCardParams = __Infer<typeof DrawCardReducer>;
export type DrawMultipleParams = __Infer<typeof DrawMultipleReducer>;
export type EndTurnParams = __Infer<typeof EndTurnReducer>;
export type ExchangeCardsParams = __Infer<typeof ExchangeCardsReducer>;
export type FlipCardParams = __Infer<typeof FlipCardReducer>;
export type JoinAsSpectatorParams = __Infer<typeof JoinAsSpectatorReducer>;
export type JoinGameParams = __Infer<typeof JoinGameReducer>;
export type LeaveGameParams = __Infer<typeof LeaveGameReducer>;
export type MeekCardParams = __Infer<typeof MeekCardReducer>;
export type MoveCardParams = __Infer<typeof MoveCardReducer>;
export type MoveCardToBottomOfDeckParams = __Infer<typeof MoveCardToBottomOfDeckReducer>;
export type MoveCardToTopOfDeckParams = __Infer<typeof MoveCardToTopOfDeckReducer>;
export type MoveCardsBatchParams = __Infer<typeof MoveCardsBatchReducer>;
export type MoveOpponentCardParams = __Infer<typeof MoveOpponentCardReducer>;
export type PregameAcknowledgeRollParams = __Infer<typeof PregameAcknowledgeRollReducer>;
export type PregameChangeDeckParams = __Infer<typeof PregameChangeDeckReducer>;
export type PregameChooseFirstParams = __Infer<typeof PregameChooseFirstReducer>;
export type PregameReadyParams = __Infer<typeof PregameReadyReducer>;
export type RemoveCounterParams = __Infer<typeof RemoveCounterReducer>;
export type RemoveTokenParams = __Infer<typeof RemoveTokenReducer>;
export type RequestRematchParams = __Infer<typeof RequestRematchReducer>;
export type RequestZoneSearchParams = __Infer<typeof RequestZoneSearchReducer>;
export type ResignGameParams = __Infer<typeof ResignGameReducer>;
export type RespondRematchParams = __Infer<typeof RespondRematchReducer>;
export type RollDiceParams = __Infer<typeof RollDiceReducer>;
export type SendChatParams = __Infer<typeof SendChatReducer>;
export type SetNoteParams = __Infer<typeof SetNoteReducer>;
export type SetPhaseParams = __Infer<typeof SetPhaseReducer>;
export type SetPlayerOptionParams = __Infer<typeof SetPlayerOptionReducer>;
export type ShuffleCardIntoDeckParams = __Infer<typeof ShuffleCardIntoDeckReducer>;
export type ShuffleDeckParams = __Infer<typeof ShuffleDeckReducer>;
export type SpawnLostSoulParams = __Infer<typeof SpawnLostSoulReducer>;
export type UnmeekCardParams = __Infer<typeof UnmeekCardReducer>;
export type UpdateCardPositionParams = __Infer<typeof UpdateCardPositionReducer>;
export type UpdateLobbyMessageParams = __Infer<typeof UpdateLobbyMessageReducer>;

