// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  gameId: __t.u64().name("game_id"),
  ownerId: __t.u64().name("owner_id"),
  zone: __t.string(),
  zoneIndex: __t.u64().name("zone_index"),
  posX: __t.string().name("pos_x"),
  posY: __t.string().name("pos_y"),
  isMeek: __t.bool().name("is_meek"),
  isFlipped: __t.bool().name("is_flipped"),
  cardName: __t.string().name("card_name"),
  cardSet: __t.string().name("card_set"),
  cardImgFile: __t.string().name("card_img_file"),
  cardType: __t.string().name("card_type"),
  brigade: __t.string(),
  strength: __t.string(),
  toughness: __t.string(),
  alignment: __t.string(),
  identifier: __t.string(),
  specialAbility: __t.string().name("special_ability"),
  reference: __t.string(),
  notes: __t.string(),
  equippedToInstanceId: __t.u64().name("equipped_to_instance_id"),
  isSoulDeckOrigin: __t.bool().name("is_soul_deck_origin"),
  isToken: __t.bool().name("is_token"),
  revealExpiresAt: __t.option(__t.timestamp()).name("reveal_expires_at"),
  originalOwnerId: __t.u64().name("original_owner_id"),
});
