// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  code: __t.string(),
  status: __t.string(),
  currentTurn: __t.u64().name("current_turn"),
  currentPhase: __t.string().name("current_phase"),
  turnNumber: __t.u64().name("turn_number"),
  format: __t.string(),
  rngCounter: __t.u64().name("rng_counter"),
  lastDiceRoll: __t.string().name("last_dice_roll"),
  createdAt: __t.timestamp().name("created_at"),
  createdBy: __t.identity().name("created_by"),
  isPublic: __t.bool().name("is_public"),
  lobbyMessage: __t.string().name("lobby_message"),
  createdByName: __t.string().name("created_by_name"),
});
