// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  code: __t.string(),
  status: __t.string(),
  currentTurn: __t.u64().name("current_turn"),
  currentPhase: __t.string().name("current_phase"),
  turnNumber: __t.u64().name("turn_number"),
  format: __t.string(),
  rngCounter: __t.u64().name("rng_counter"),
  lastDiceRoll: __t.string().name("last_dice_roll"),
  createdAt: __t.timestamp().name("created_at"),
  createdBy: __t.identity().name("created_by"),
  isPublic: __t.bool().name("is_public"),
  lobbyMessage: __t.string().name("lobby_message"),
  createdByName: __t.string().name("created_by_name"),
  pregamePhase: __t.string().name("pregame_phase"),
  pregameReady0: __t.bool().name("pregame_ready_0"),
  pregameReady1: __t.bool().name("pregame_ready_1"),
  rollWinner: __t.string().name("roll_winner"),
  rollResult0: __t.u64().name("roll_result_0"),
  rollResult1: __t.u64().name("roll_result_1"),
  rematchRequestedBy: __t.string().name("rematch_requested_by"),
  rematchDeckId0: __t.string().name("rematch_deck_id_0"),
  rematchDeckData0: __t.string().name("rematch_deck_data_0"),
  rematchDeckId1: __t.string().name("rematch_deck_id_1"),
  rematchDeckData1: __t.string().name("rematch_deck_data_1"),
  rematchResponse: __t.string().name("rematch_response"),
  rematchCode: __t.string().name("rematch_code"),
  disconnectTimeoutFired: __t.bool().name("disconnect_timeout_fired"),
  choosingDeadlineMicros: __t.u64().name("choosing_deadline_micros"),
});
