// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  gameId: __t.u64().name("game_id"),
  playerId: __t.u64().name("player_id"),
  actionType: __t.string().name("action_type"),
  payload: __t.string(),
  turnNumber: __t.u64().name("turn_number"),
  phase: __t.string(),
  timestamp: __t.timestamp(),
});
