// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  gameId: __t.u64().name("game_id"),
  identity: __t.identity(),
  seat: __t.u64(),
  deckId: __t.string().name("deck_id"),
  displayName: __t.string().name("display_name"),
  supabaseUserId: __t.string().name("supabase_user_id"),
  isConnected: __t.bool().name("is_connected"),
  autoRouteLostSouls: __t.bool().name("auto_route_lost_souls"),
  handRevealed: __t.bool().name("hand_revealed"),
  pendingDeckData: __t.string().name("pending_deck_data"),
});
