// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  gameId: __t.u64().primaryKey().name("game_id"),
  activeSeat: __t.u64().name("active_seat"),
  starsDone0: __t.bool().name("stars_done_0"),
  starsDone1: __t.bool().name("stars_done_1"),
  soulsDone0: __t.bool().name("souls_done_0"),
  soulsDone1: __t.bool().name("souls_done_1"),
});
