// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CardCounter = __t.object("CardCounter", {
  id: __t.u64(),
  cardInstanceId: __t.u64(),
  color: __t.string(),
  count: __t.u64(),
});
export type CardCounter = __Infer<typeof CardCounter>;

export const CardInstance = __t.object("CardInstance", {
  id: __t.u64(),
  gameId: __t.u64(),
  ownerId: __t.u64(),
  zone: __t.string(),
  zoneIndex: __t.u64(),
  posX: __t.string(),
  posY: __t.string(),
  isMeek: __t.bool(),
  isFlipped: __t.bool(),
  cardName: __t.string(),
  cardSet: __t.string(),
  cardImgFile: __t.string(),
  cardType: __t.string(),
  brigade: __t.string(),
  strength: __t.string(),
  toughness: __t.string(),
  alignment: __t.string(),
  identifier: __t.string(),
  specialAbility: __t.string(),
  notes: __t.string(),
});
export type CardInstance = __Infer<typeof CardInstance>;

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  gameId: __t.u64(),
  senderId: __t.u64(),
  text: __t.string(),
  sentAt: __t.timestamp(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const DisconnectTimeout = __t.object("DisconnectTimeout", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  gameId: __t.u64(),
  playerId: __t.u64(),
});
export type DisconnectTimeout = __Infer<typeof DisconnectTimeout>;

export const Game = __t.object("Game", {
  id: __t.u64(),
  code: __t.string(),
  status: __t.string(),
  currentTurn: __t.u64(),
  currentPhase: __t.string(),
  turnNumber: __t.u64(),
  format: __t.string(),
  rngCounter: __t.u64(),
  lastDiceRoll: __t.string(),
  createdAt: __t.timestamp(),
  createdBy: __t.identity(),
  isPublic: __t.bool(),
  lobbyMessage: __t.string(),
  createdByName: __t.string(),
  pregamePhase: __t.string(),
  pregameReady0: __t.bool(),
  pregameReady1: __t.bool(),
  rollWinner: __t.string(),
  rollResult0: __t.u64(),
  rollResult1: __t.u64(),
  rematchRequestedBy: __t.string(),
  rematchDeckId0: __t.string(),
  rematchDeckData0: __t.string(),
  rematchDeckId1: __t.string(),
  rematchDeckData1: __t.string(),
  rematchResponse: __t.string(),
  rematchCode: __t.string(),
});
export type Game = __Infer<typeof Game>;

export const GameAction = __t.object("GameAction", {
  id: __t.u64(),
  gameId: __t.u64(),
  playerId: __t.u64(),
  actionType: __t.string(),
  payload: __t.string(),
  turnNumber: __t.u64(),
  phase: __t.string(),
  timestamp: __t.timestamp(),
});
export type GameAction = __Infer<typeof GameAction>;

export const Player = __t.object("Player", {
  id: __t.u64(),
  gameId: __t.u64(),
  identity: __t.identity(),
  seat: __t.u64(),
  deckId: __t.string(),
  displayName: __t.string(),
  supabaseUserId: __t.string(),
  isConnected: __t.bool(),
  autoRouteLostSouls: __t.bool(),
  pendingDeckData: __t.string(),
});
export type Player = __Infer<typeof Player>;

export const Spectator = __t.object("Spectator", {
  id: __t.u64(),
  gameId: __t.u64(),
  identity: __t.identity(),
  displayName: __t.string(),
});
export type Spectator = __Infer<typeof Spectator>;

export const ZoneSearchRequest = __t.object("ZoneSearchRequest", {
  id: __t.u64(),
  gameId: __t.u64(),
  requesterId: __t.u64(),
  targetPlayerId: __t.u64(),
  zone: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type ZoneSearchRequest = __Infer<typeof ZoneSearchRequest>;

