// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CardCounter = __t.object("CardCounter", {
  id: __t.u64(),
  cardInstanceId: __t.u64(),
  color: __t.string(),
  count: __t.u64(),
});
export type CardCounter = __Infer<typeof CardCounter>;

export const CardInstance = __t.object("CardInstance", {
  id: __t.u64(),
  gameId: __t.u64(),
  ownerId: __t.u64(),
  zone: __t.string(),
  zoneIndex: __t.u64(),
  posX: __t.string(),
  posY: __t.string(),
  isMeek: __t.bool(),
  isFlipped: __t.bool(),
  cardName: __t.string(),
  cardSet: __t.string(),
  cardImgFile: __t.string(),
  cardType: __t.string(),
  brigade: __t.string(),
  strength: __t.string(),
  toughness: __t.string(),
  alignment: __t.string(),
  identifier: __t.string(),
  specialAbility: __t.string(),
  reference: __t.string(),
  notes: __t.string(),
  equippedToInstanceId: __t.u64(),
  isSoulDeckOrigin: __t.bool(),
  isToken: __t.bool(),
  revealExpiresAt: __t.option(__t.timestamp()),
  originalOwnerId: __t.u64(),
  revealStartedAt: __t.option(__t.timestamp()),
  originZone: __t.string(),
  originPosX: __t.string(),
  originPosY: __t.string(),
  outlineColor: __t.string(),
  imitatingName: __t.string(),
});
export type CardInstance = __Infer<typeof CardInstance>;

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  gameId: __t.u64(),
  senderId: __t.u64(),
  text: __t.string(),
  sentAt: __t.timestamp(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const ChooseFirstTimeout = __t.object("ChooseFirstTimeout", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  gameId: __t.u64(),
});
export type ChooseFirstTimeout = __Infer<typeof ChooseFirstTimeout>;

export const CleanupSchedule = __t.object("CleanupSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type CleanupSchedule = __Infer<typeof CleanupSchedule>;

export const DisconnectTimeout = __t.object("DisconnectTimeout", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  gameId: __t.u64(),
  playerId: __t.u64(),
});
export type DisconnectTimeout = __Infer<typeof DisconnectTimeout>;

export const Emote = __t.object("Emote", {
  id: __t.u64(),
  gameId: __t.u64(),
  senderId: __t.u64(),
  kind: __t.string(),
  createdAt: __t.timestamp(),
});
export type Emote = __Infer<typeof Emote>;

export const ForgeConfig = __t.object("ForgeConfig", {
  id: __t.u64(),
  serverIdentityHex: __t.string(),
});
export type ForgeConfig = __Infer<typeof ForgeConfig>;

export const ForgeGame = __t.object("ForgeGame", {
  gameId: __t.u64(),
});
export type ForgeGame = __Infer<typeof ForgeGame>;

export const ForgeSeatAuth = __t.object("ForgeSeatAuth", {
  id: __t.u64(),
  code: __t.string(),
  identityHex: __t.string(),
  authorizedAtMicros: __t.u64(),
});
export type ForgeSeatAuth = __Infer<typeof ForgeSeatAuth>;

export const Game = __t.object("Game", {
  id: __t.u64(),
  code: __t.string(),
  status: __t.string(),
  currentTurn: __t.u64(),
  currentPhase: __t.string(),
  turnNumber: __t.u64(),
  format: __t.string(),
  rngCounter: __t.u64(),
  lastDiceRoll: __t.string(),
  createdAt: __t.timestamp(),
  createdBy: __t.identity(),
  isPublic: __t.bool(),
  lobbyMessage: __t.string(),
  createdByName: __t.string(),
  pregamePhase: __t.string(),
  pregameReady0: __t.bool(),
  pregameReady1: __t.bool(),
  rollWinner: __t.string(),
  rollResult0: __t.u64(),
  rollResult1: __t.u64(),
  rematchRequestedBy: __t.string(),
  rematchDeckId0: __t.string(),
  rematchDeckData0: __t.string(),
  rematchDeckId1: __t.string(),
  rematchDeckData1: __t.string(),
  rematchParagon0: __t.string(),
  rematchParagon1: __t.string(),
  rematchResponse: __t.string(),
  rematchCode: __t.string(),
  disconnectTimeoutFired: __t.bool(),
  choosingDeadlineMicros: __t.u64(),
  playingStartedAtMicros: __t.u64(),
  pauseRequestedBy: __t.string(),
  pauseRequestType: __t.string(),
  pauseStartedAtMicros: __t.u64(),
  totalPausedMicros: __t.u64(),
  battleState: __t.string(),
  battleAttackerSeat: __t.string(),
  lastBattlePlayBySeat: __t.string(),
});
export type Game = __Infer<typeof Game>;

export const GameAction = __t.object("GameAction", {
  id: __t.u64(),
  gameId: __t.u64(),
  playerId: __t.u64(),
  actionType: __t.string(),
  payload: __t.string(),
  turnNumber: __t.u64(),
  phase: __t.string(),
  timestamp: __t.timestamp(),
});
export type GameAction = __Infer<typeof GameAction>;

export const Player = __t.object("Player", {
  id: __t.u64(),
  gameId: __t.u64(),
  identity: __t.identity(),
  seat: __t.u64(),
  deckId: __t.string(),
  displayName: __t.string(),
  paragon: __t.string(),
  supabaseUserId: __t.string(),
  isConnected: __t.bool(),
  autoRouteLostSouls: __t.bool(),
  handRevealed: __t.bool(),
  pendingDeckData: __t.string(),
  revealedCards: __t.string(),
  reserveRevealed: __t.bool(),
  handRevealSnapshot: __t.string(),
  shareHandWithSpectators: __t.bool(),
});
export type Player = __Infer<typeof Player>;

export const Spectator = __t.object("Spectator", {
  id: __t.u64(),
  gameId: __t.u64(),
  identity: __t.identity(),
  displayName: __t.string(),
});
export type Spectator = __Infer<typeof Spectator>;

export const SpectatorBan = __t.object("SpectatorBan", {
  id: __t.u64(),
  gameId: __t.u64(),
  identity: __t.identity(),
  bannedBySeat: __t.u64(),
  bannedAt: __t.timestamp(),
});
export type SpectatorBan = __Infer<typeof SpectatorBan>;

export const SpectatorHandRequest = __t.object("SpectatorHandRequest", {
  id: __t.u64(),
  gameId: __t.u64(),
  spectatorId: __t.u64(),
  spectatorName: __t.string(),
  requestedAt: __t.timestamp(),
});
export type SpectatorHandRequest = __Infer<typeof SpectatorHandRequest>;

export const SpectatorHandRequestExpiry = __t.object("SpectatorHandRequestExpiry", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  requestId: __t.u64(),
});
export type SpectatorHandRequestExpiry = __Infer<typeof SpectatorHandRequestExpiry>;

export const ZoneSearchRequest = __t.object("ZoneSearchRequest", {
  id: __t.u64(),
  gameId: __t.u64(),
  requesterId: __t.u64(),
  targetPlayerId: __t.u64(),
  zone: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  action: __t.string(),
  actionParams: __t.string(),
});
export type ZoneSearchRequest = __Infer<typeof ZoneSearchRequest>;

