// GENERATED by scripts/forge-extract-template.py from the design team's Illustrator
// card template (v3.7). Do not edit by hand; rerun `make forge-frames`.
// Canvas is the 2.5 x 3.5 in trim box at 300 dpi. Rects: {x, y, w, h, r} in canvas px.

export const CANVAS = { w: 750, h: 1050 } as const;
export const BORDER_STROKE = 6.25;

export const RECTS = {
  border: {x: 37.5, y: 37.5, w: 675.0, h: 975.0, r: 39.6},
  art: {x: 75.0, y: 110.7, w: 600.0, h: 548.5, r: 32.1},
  textBox: {x: 75.0, y: 668.0, w: 600.0, h: 284.2, r: 32.5},
  textInset: {x: 90.0, y: 690.9, w: 570.0, h: 254.7, r: 0.0},
  idBubble: {x: 75.0, y: 648.8, w: 600.0, h: 31.5, r: 15.8},
  leftBox: {x: 35.5, y: 32.4, w: 167.4, h: 132.3, r: 0.0},
  rightBox: {x: 543.6, y: 25.5, w: 174.7, h: 143.0, r: 0.0},
  statText: {x: 58.0, y: 34.3, w: 118.4, h: 33.9, r: 0.0},
  classIcons: {x: 33.3, y: 133.3, w: 100.0, h: 120.8, r: 0.0},
  title: {x: 212.5, y: 51.9, w: 462.5, h: 56.0, r: 0.0},
  credits: {x: 212.5, y: 956.3, w: 462.5, h: 50.0, r: 0.0},
} as const;

// Where the type and class icons sit, from the template's raster placements: type
// icons inside the top-left box (`…Stats` = the lower slot under strength/toughness),
// the class shield and territory plate below it. Rects are the rasters' own aspect.
export const ICON_RECTS = {
  cross: {x: 92.4, y: 83.0, w: 53.6, h: 61.0}, // 75% of the template slot, as printed
  dragon: {x: 59.4, y: 67.2, w: 122.4, h: 96.6},
  skull: {x: 85.9, y: 51.2, w: 63.3, h: 88.8},
  skullStats: {x: 85.9, y: 72.0, w: 63.3, h: 88.8},
  bible: {x: 74.3, y: 70.8, w: 88.9, h: 60.2},
  bibleStats: {x: 74.9, y: 83.3, w: 88.9, h: 60.2},
  fortress: {x: 56.7, y: 62.4, w: 125.1, h: 63.9},
  site: {x: 44.4, y: 58.3, w: 146.0, h: 72.0},
  shield: {x: 33.9, y: 179.5, w: 88.9, h: 104.3},
  territory: {x: 25.5, y: 182.0, w: 106.5, h: 46.8},
} as const;

// Ability box gradient: light until `light`% of the box, black from `dark`%.
export const GRADIENT_ROWS = {
  2: { light: 73, dark: 86 },
  3: { light: 64, dark: 77 },
  4: { light: 54, dark: 68 },
  5: { light: 47, dark: 60 },
} as const;

// Icon-box fills, CMYK from the template converted through its SWOP profile.
// red / teal are not in the template: hue-shifted from crimson / blue.
export const BRIGADE_BOX_HEX = {
  "pale-green": "#d1e5a9",
  "orange": "#fab066",
  "gray": "#a8b5af",
  "crimson": "#ed3d7a",
  "brown": "#a16d3a",
  "black": "#292929",
  "white": "#ffffff",
  "silver": "#aaacae",
  "purple": "#a74f9c",
  "green": "#29ac57",
  "gold": "#fed655",
  "clay": "#dba8a8",
  "blue": "#364d95",
  "red": "#ed493d", // synthesized
  "teal": "#36958e", // synthesized
} as const;
