#!/usr/bin/env python3
"""Generate app/forge/lib/fontMetrics.ts: advance widths of the Forge preview's body faces
(Arimo Bold for abilities, Arimo Italic for scripture) so the preview can wrap text the way
the browser will and tell whether an ability fits its printed box. Stdlib only.

    python3 scripts/forge-font-metrics.py
"""
import json
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONTS = {"bold": "Arimo-Bold.ttf", "italic": "Arimo-Italic.ttf"}
# ASCII printable plus the punctuation card text actually uses.
CHARS = [chr(c) for c in range(32, 127)] + list("‘’“”–—… é")


def tables(b):
    n = struct.unpack(">H", b[4:6])[0]
    return {b[12 + 16 * i:16 + 16 * i].decode(): struct.unpack(">II", b[20 + 16 * i:28 + 16 * i]) for i in range(n)}


def cmap4(b, off):
    ntab = struct.unpack(">H", b[off + 2:off + 4])[0]
    for i in range(ntab):
        sub = off + struct.unpack(">HHI", b[off + 4 + 8 * i:off + 12 + 8 * i])[2]
        if struct.unpack(">H", b[sub:sub + 2])[0] != 4:
            continue
        segx2 = struct.unpack(">H", b[sub + 6:sub + 8])[0]
        seg = segx2 // 2
        ends = struct.unpack(f">{seg}H", b[sub + 14:sub + 14 + segx2])
        p = sub + 16 + segx2
        starts = struct.unpack(f">{seg}H", b[p:p + segx2]); p += segx2
        deltas = struct.unpack(f">{seg}h", b[p:p + segx2]); p += segx2
        ros = p
        ro = struct.unpack(f">{seg}H", b[p:p + segx2])
        m = {}
        for s in range(seg):
            for c in range(starts[s], min(ends[s], 0xFFFE) + 1):
                if ro[s] == 0:
                    g = (c + deltas[s]) & 0xFFFF
                else:
                    gi = ros + 2 * s + ro[s] + 2 * (c - starts[s])
                    g = struct.unpack(">H", b[gi:gi + 2])[0]
                    if g:
                        g = (g + deltas[s]) & 0xFFFF
                if g:
                    m[chr(c)] = g
        return m
    raise SystemExit("no format-4 cmap")


def advances(path):
    b = path.read_bytes()
    t = tables(b)
    upem = struct.unpack(">H", b[t["head"][0] + 18:t["head"][0] + 20])[0]
    nhm = struct.unpack(">H", b[t["hhea"][0] + 34:t["hhea"][0] + 36])[0]
    hm = t["hmtx"][0]
    cm = cmap4(b, t["cmap"][0])

    def adv(ch):
        g = min(cm.get(ch, 0), nhm - 1)
        return struct.unpack(">H", b[hm + 4 * g:hm + 4 * g + 2])[0]

    return upem, {ch: adv(ch) for ch in CHARS}


def main():
    out = ["// GENERATED by scripts/forge-font-metrics.py from public/forge/fonts — do not edit.",
           "// Advance widths in font units (1000 per em) for the preview's body faces, used by",
           "// textFit.ts to wrap abilities and scripture the way the browser will.", "",
           "export const FONT_UPEM = 1000;", ""]
    for key, file in FONTS.items():
        upem, adv = advances(ROOT / "public/forge/fonts" / file)
        scaled = {ch: round(w * 1000 / upem) for ch, w in adv.items()}
        entries = ", ".join(f"[{json.dumps(ch, ensure_ascii=False)}, {w}]" for ch, w in scaled.items())
        out.append(f"export const {key.upper()}_ADVANCES: ReadonlyMap<string, number> = new Map([{entries}]);")
        out.append("")
    (ROOT / "app/forge/lib/fontMetrics.ts").write_text("\n".join(out), encoding="utf-8")
    print("wrote app/forge/lib/fontMetrics.ts")


if __name__ == "__main__":
    main()
