/**
 * Generates lib/wp/categoryMap.ts from the WordPress WXR export (spec §1).
 * Dev-only; the output is committed so runtime never needs the export.
 * Usage: npx tsx scripts/generate-wp-redirects.ts --wxr <path>
 */
import { readFileSync, writeFileSync } from "node:fs";
import { parseArgs } from "node:util";
import { XMLParser } from "fast-xml-parser";
import he from "he";

const { values } = parseArgs({ options: { wxr: { type: "string" } } });
if (!values.wxr) throw new Error("--wxr <path to WXR export> is required");

const parser = new XMLParser({
  ignoreAttributes: false,
  parseTagValue: false,
  isArray: (name) => name === "wp:category",
});
type Node = Record<string, unknown>;
const text = (v: unknown): string =>
  v == null ? "" : typeof v === "object" ? text((v as Node)["#text"]) : String(v);

const channel = parser.parse(readFileSync(values.wxr, "utf8")).rss.channel as Node;
const cats = ((channel["wp:category"] as Node[]) ?? [])
  .map((c) => ({
    termId: text(c["wp:term_id"]).trim(),
    slug: text(c["wp:category_nicename"]).trim(),
    name: he.decode(text(c["wp:cat_name"])).replace(/\s+/g, " ").trim(),
  }))
  .filter((c) => c.termId && c.slug && c.name)
  .sort((a, b) => a.slug.localeCompare(b.slug));

const record = (entries: [string, string][]) =>
  "{\n" + entries.map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join("\n") + "\n}";

writeFileSync(
  "lib/wp/categoryMap.ts",
  `// GENERATED by scripts/generate-wp-redirects.ts from the WordPress WXR export — do not edit by hand.
// WP category nicename (URL slug) → the tag name the import stored on posts.
export const CATEGORY_BY_SLUG: Record<string, string> = ${record(cats.map((c) => [c.slug, c.name]))};

// WP term id (the ?cat= query value) → the same tag name.
export const CATEGORY_BY_TERM_ID: Record<string, string> = ${record(
    [...cats].sort((a, b) => Number(a.termId) - Number(b.termId)).map((c) => [c.termId, c.name]),
  )};
`,
);
console.log(`wrote lib/wp/categoryMap.ts with ${cats.length} categories`);
